name: Environmet Secures

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    env:
      REACT_APP_SHAZAM_CORE_API_HOST: ${{ secrets.REACT_APP_SHAZAM_CORE_API_HOST }}
      REACT_APP_SHAZAM_CORE_API_KEY: ${{ secrets.REACT_APP_SHAZAM_CORE_API_KEY }}
